# name of the project
projectName: "iow-allgemein"
# name of the application or service
applicationName: "graph-server"
# name of the docker image
dockerImageName: "wdfn_graph_server"
# location of the Dockerfile
buildContext: "./"
# port that is exposed by your container
containerPort: 2929
# docker image path in artifactory
artifactoryPath: "graph-server"
# complete github url
gitRepoUrl: "https://github.com/usgs/wdfn-graph-server.git"
# github credentials
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
# maximum amount of RAM for running Docker containers in the service
memory: 1024
# string parameter specifying a path that ALB should use to verify that your application is alive
healthCheck: "/api/graph-images/status/"
# name of the deploy job to trigger
deployJobName: "wdfn-graph-server-deploy"
configRepoPath: "wma/docker/wdfn/wdfn-graph-server"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/api/graph-images/*"
    priority: 503
tags:
  wma:costCenter: TBD
  wma:organization: IOW
  wma:contact: "jkreft@usgs.gov"
  wma:taggingVersion: 0.0.1
  wma:project_id: iow
